### ISSUE TITLE
How to use this with bootstrap?

### ISSUE THREAD

**Issue by andersontr15** [webpack-contrib/purifycss-webpack#100]
How to use this with bootstrap and react? I'm importing bootstrap into a bundle right now.

**Comment by bebraw** [comment]
How do you refer to Bootstrap classes?

**Comment by andersontr15** [comment]
With react's `className` attribute.

**Comment by bebraw** [comment]
@andersontr15 Ok, as long as it's `className="foobar"` kind of style (nothing dynamic), the tooling just might pick it up. Use the `verbose` option to get more insight.

If you can't get it to work, please set up a small repository for me to study.

**Comment by andersontr15** [comment]
Yeah I was able to get it to work with bootstrap but now my css modules aren't being picked up even with whitelisting it with '*purify*'

**Comment by bebraw** [comment]
CSS Modules takes some extra effort. Please see the README for details.

**Comment by andersontr15** [comment]
Got it to work. Don't know if anyone has tried this, but I had to add the .json files emitted by the `postcss- modules `to the paths array for `purifycss` to get it to work.

**Comment by bebraw** [comment]
@andersontr15 If you have time, please make a doc PR about that. 👍
