### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by JPortegijs** [webpack-contrib/purifycss-webpack#103]
Hello,

How would I include multiple paths? I have this now but gives me errors.
new PurifyCSSPlugin({
            paths: [
                glob.sync(path.join(__dirname, '*.php')),
                glob.sync(path.join(__dirname, 'partials/*.php')),
            ],
            minimize: inProduction
        }),

Any help would be appreciated!

Thanks in advance.

**Comment by bebraw** [comment]
Now you have an array of arrays. It expects a flat array. Most likely you want to concatenate the result of those `glob.sync` calls or flatten it.

**Comment by JPortegijs** [comment]
I think I found a workaround and use https://github.com/jpillora/node-glob-all instead of the regular glob. This allows me to look into multiple paths. My code looks like this now:

paths: glob.sync([
     path.join(__dirname, '*.php'),
     path.join(__dirname, 'partials/*.php')
]),

This seems to do the trick for me.

**Comment by bebraw** [comment]
@JPortegijs Cool. Please PR a README fix. 👍

**Comment by stephan-v** [comment]
Example not working for me, the CSS simpy isn't being built when I try to use an array. Otherwise it works fine.

**Comment by bebraw** [comment]
@stephan-v Can you open a separate issue? There's not enough information to debug.

**Comment by stephan-v** [comment]
@bebraw I have create a stackoverflow post since I think that was preferred in another issue:

https://stackoverflow.com/questions/44301416/purifycss-webpack-not-creating-css-output-with-multiple-paths
