### ISSUE TITLE
Error message missing } for nested CSS

### ISSUE THREAD

**Issue by scriptPilot** [webpack-contrib/purifycss-webpack#107]
Hey , thanks for the great piece of code!

One point - with the following CSS code, I get the error "... missing } ...":

```
.kitchen-sink-material @media (max-width: 767px) {
  .kitchen-sink-material #ks-picker-date-container .picker-items {
    font-size: 21px;
  }
  .kitchen-sink-material #ks-picker-date-container .picker-item {
    height: 36px;
    line-height: 36px;
  }
  .kitchen-sink-material #ks-picker-date-container .picker-item span {
    padding: 0 6px;
  }
}
```

Is there anything wrong with the CSS, as it should be allowed since CSS3 ?

Regards!

**Comment by bebraw** [comment]
Can you test against Purify directly? It might not support the syntax. Maybe you could preprocess it somehow (postcss).

**Comment by TheLarkInn** [comment]
Nested brackets?
