### ISSUE TITLE
peerDependencies WARNING purifycss-webpack@0.7.0

### ISSUE THREAD

**Issue by jlzhang-zy** [webpack-contrib/purifycss-webpack#109]
When I upgraded purifycss-webpack to 0.7.0, I got this error:

peerDependencies WARNING purifycss-webpack@0.7.0 requires a peer of purify-css@>                       = 1.0.0 < 2.0.0 but none was installed

@bebraw

**Comment by michael-ciniawsky** [comment]
@jlzhang-zy Did you install `purify-css` within this semver range? It's up to the user to handle the version of `purify-css` in use

**Comment by bebraw** [comment]
Please see [the changelog](https://github.com/webpack-contrib/purifycss-webpack/blob/master/CHANGELOG.md#070--2017-05-16).

**Comment by jlzhang-zy** [comment]
@michael-ciniawsky @bebraw thank you guys!
