### ISSUE TITLE
Trouble with class names containing numerals

### ISSUE THREAD

**Issue by Cobrarosa** [webpack-contrib/purifycss-webpack#119]
OS: Windows 10
Node: v6.9.5
Webpack: 3.4.1

New to webpack. Trying PurifyCSS. Using class-names with numerals in .scss files will be compiled in the .css file, regardless if the class is present in the template files or not.

Example in template
`<div class="test"></div>`

Example in .scss file
`.test2 { color: red }`

Output in .css file
`.test2 { color: red }`

However, changing the .scss to "test" and the class in the template to "testy" will yield the desired result (omitting the "test" class from the compiled css).

It seems PurifyCSS does not recognize class names with numerals in them. Seen other issues addressing this issue when using CSS frameworks like bootstrap, who has plenty of numeral-based class-names. 

Is there something that can be done about this?

**Comment by zackkrida** [comment]
FYI this is an outstanding with the core purifycss library: 

- https://github.com/purifycss/purifycss/issues/147#issuecomment-319375939
- https://github.com/purifycss/purifycss/issues/118

**Comment by michael-ciniawsky** [comment]
@Cobrarosa See @zackkrida's comment. @zackkrida Thx 👍
