### ISSUE TITLE
Too much css class rules getting stripped out 

### ISSUE THREAD

**Issue by iamanoopc** [webpack-contrib/purifycss-webpack#123]
Check out this repo
[REPO](https://github.com/iamanoopc/debloat-bootstrap)

![screen1](https://user-images.githubusercontent.com/10864338/30319383-4d308d6e-97e2-11e7-91fd-23b13ccdbd16.JPG)
![screen2](https://user-images.githubusercontent.com/10864338/30319398-54448d12-97e2-11e7-9b05-f5f4ae3565ae.JPG)

I think it is self explanatory, clone the repo and run `npm install && webpack`.
Then uncomment the purifyplugin from webpack.config.js file and run `webpack` again.

**Comment by DracotMolver** [comment]
In your code you are extrancting only files ended in .scss
