### ISSUE TITLE
Example for migrating from purifycss/purifycss-webpack-plugin

### ISSUE THREAD

**Issue by t47io** [webpack-contrib/purifycss-webpack#75]
Hi, I had no luck migrating from the old `purifycss/purifycss-webpack-plugin` to this new `webpack-contrib/purifycss-webpack`. Can anyone spot what's wrong?

My old config for `purifycss/purifycss-webpack-plugin`:
```
    new PurifyCSSPlugin({
      basePath: rootPath,
      paths: [
       'app/**/*.jsx',
       'app/**/*.json',
       'public/**/*.html'
      ],
      purifyOptions: {
        minify: true,
        info:true,
        rejected: true
      }
    }),
```

New config for `webpack-contrib/purifycss-webpack`:
```
    new PurifyCSSPlugin({
      paths: [
        ...(glob.sync(`${rootPath}/app/**/*.jsx`)),
        ...(glob.sync(`${rootPath}/app/**/*.json`)),
        ...(glob.sync(`${rootPath}/public/**/*.html`))
      ],
      purifyOptions: {
        minify: true,
        info: true,
        rejected: true
      }
    }),
```

No effect for any changes. Not sure if I got the `paths` correct. Should it combine the old `basePath` and `paths`, but using `glob`?

P.S> `{purifyOptions: { info: true} }` as above does not work. Have to use `verbose: true`.

P.P.S> For my config, all the verbose I got is an empty line like this:
```
Assets to purify:
```

**Comment by t47io** [comment]
using:
```
webpack          2.2.1
purifycss-webpack   0.4.2
extract-text-webpack-plugin 2.0.0-rc.3
```

used to be `purifycss-webpack-plugin 2.0.3`

**Comment by bebraw** [comment]
I would need a little project to study to say anything concrete. Maybe someone else has a better idea.

**Comment by martin-svk** [comment]
Hi, I have similar problem. Looks like is is very hard to figure out how to set the `path` / `paths` attribute. Tried several modifications, but no luck.

**Comment by bebraw** [comment]
Little standalone projects would help to debug these.

**Comment by gw0** [comment]
I think that the problem could be that `glob.sync()` is evaluated before Webpack generates those files (that could contain a hash or other non-static name).
