### ISSUE TITLE
Make sure {purifyOptions: { info: true} } works

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/purifycss-webpack#76]
`verbose` flag overrides that but it should also work standalone.

**Comment by johakr** [comment]
Hi @bebraw, is this issue still valid?

As far as i see, if you pass `{purifyOptions: { info: true} }` it would always be passed down to purifycss as `true`, no matter `verbose` is set to `true` or `false`.

**Comment by bebraw** [comment]
Yeah. It's a specification problem. Let's skip and re-open if someone thinks otherwise.
