### ISSUE TITLE
Plugin is not properly removing unused classes like for example from bootstrap.

### ISSUE THREAD

**Issue by gfunk1230** [webpack-contrib/purifycss-webpack#82]
So when running the plugin I am not seeing any significant reduction and in fact I am still seeing references to css that isn't being used via bootstrap. I have followed all directions and I am seeing other experiencing the same issue such as here: https://github.com/webpack-contrib/purifycss-webpack/issues/49 

![screen shot 2017-02-10 at 11 51 43 am](https://cloud.githubusercontent.com/assets/6556242/23181072/88044124-f841-11e6-8f51-eab526344961.png)

**Comment by bebraw** [comment]
It's hard to say anything concrete based on output alone. I would need as simple as possible project to study that fails to pick up some class to say more.

**Comment by bebraw** [comment]
Feel free to re-open with a proper example.
