### ISSUE TITLE
Don't remove not reference css class

### ISSUE THREAD

**Issue by Kikobeats** [webpack-contrib/purifycss-webpack#98]
Hello,

I  have detected some styles of my boilerplate are not removed.

I isolate the problem in a branch called [bug](https://github.com/Kikobeats/react-boilerplatinum/tree/bug).

I have third party scss that compiles to css. PurifyCSS removed not used classes correctly.

But also I have css classes that I don't use. I created the class [.foo-bar](https://github.com/Kikobeats/react-boilerplatinum/blob/bug/src/app/index.scss#L3) intentionally for see if will be removed in the final bundle, and this doesn't happen!

Of course the class is not used.

My configuration is [here](https://github.com/Kikobeats/react-boilerplatinum/blob/bug/webpack.config.js#L80). I think is correct, obviously the file is included in the glob pattern.

Steps for reproduce this:

```
git clone -b bug git@github.com:Kikobeats/react-boilerplatinum.git
npm install & npm run build
```

After that the project will be compiled and check if `.foo-bar` is in the output, this means if it was removed.

Any idea?

**Comment by bebraw** [comment]
The clue is likely in

> I have third party scss that compiles to css. PurifyCSS removed not used classes correctly.

There must be some piece of logic related to this missing. Maybe the question is, how could Purify become aware of the compiled SCSS?

**Comment by Kikobeats** [comment]
but that's the point!

I have scss and webpack convert it into css.

Then I have plain css.

Purify is removing the unused css from the scss, but not the raw not used css.

**Comment by bebraw** [comment]
Yeah, implementation-wise the problem is that Purify accepts files as input. This is fine as long as we are dealing with regular CSS since we can just pass paths to the files to Purify and it will pick them up.

It gets complicated when you need to preprocess. Purify still expects paths but it's this portion that needs something extra to make your use case work. Maybe we have to write a temporary file with the rules or use Purify differently somehow.

**Comment by Kikobeats** [comment]
The pipeline that I uses for convert scss to css is [here](https://github.com/Kikobeats/react-boilerplatinum/blob/bug/webpack.config.js#L47).

Can I do something for be possible purify removed the unnecessary CSS?

**Comment by bebraw** [comment]
Ah, like that... You would have to dig into the plugin code to tell any better. I'm extremely strapped on time these days. 😞

**Comment by Kikobeats** [comment]
I found the bug!

The configuration for that was:

```
paths: glob.sync('src/app/**/*', { nodir: true }),
styleExtensions: ['.css'],
moduleExtensions: ['.js', '.scss', '.html'],
```

The problem: Even the class  `.foo-bar` is not referenced, the glob pattern match the file and the file is a referencer for hiself.

I updated for avoid include the file in the pattern with:

```
paths: glob.sync('src/app/**/*.js', { nodir: true }),
```

and that's all!

**Comment by bebraw** [comment]
Ok, cool to hear. I wonder if there's anything that could be done to make it harder to bump into this type of issue. 😄
